version: '4.1'
services:
  db:
    image: postgres:13.1-alpine
    container_name: cats-inventory
    ports:
      - "5432:5432"
    expose:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=cats_inventory
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./sql/postgres_schema.sql:/docker-entrypoint-initdb.d/postgres_schema.sql